language: node_js
node_js:
  - "6.5.0"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build

script: ng e2e